# .github/workflows/main.yml
name: CI Basico

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Mostrar archivos
      run: ls -la

    - name: Ejecutar prueba simple
      run: echo "Hola CI/CD desde GitHub Actions "
